---
- name: Join workers to cluster
  hosts: w-nodes-join
  become: true
  become_user: root

#Use these variables to join to an existing cluster
#  vars:
#    loadbalancer: "130.185.121.10"
#    token: "abcdef.0123456789abcdef"
#    token_hash: "sha256:be705b73c4de9089d9df0419ac8ed2de69add53dc6a415ed0f812b749b94bb6a"

  tasks:
  - name: Join worker nodes
    shell: |
      #Paste your command here
      kubeadm join 130.185.121.10:6443 --token abcdef.0123456789abcdef \
        --discovery-token-ca-cert-hash sha256:be705b73c4de9089d9df0419ac8ed2de69add53dc6a415ed0f812b749b94bb6a

#  - name: Join to an existing cluster by variables
#    shell: |
#      kubeadm join "{{ loadbalancer }}":6443 \
#        --token "{{ token }}" \
#        --discovery-token-ca-cert-hash "{{ token_hash }}"
